### PR TITLE
fix circ_topo

### LINKED ISSUE #123: circular topoplot - label not working
5b95213d
the label in the center is currently not working

### PR DESCRIPTION
**Pull request by vladdez**
Solved issues
- #165 
- #123 
- #167 

- added `sortval_xlabel` to erpimage

### CODE REVIEW

File: src/plot_erpimage.jl [hunk 1]
```diff
@@ -128,9 +128,7 @@ function plot_erpimage!(
             xautolimitmargin = (0, 0),
             sub_config1.axis...,
```
Comment (behinger) [inline src/plot_erpimage.jl:129]: it does make any sense to add here the axis, the fields already have those values.

Wouldnt you rather add the `kwargs` here to make it possible to overwrite values? (same for sub_config2) 
Potentially, if you want users to be able to modify each of the three plots with different values, you'd need t think about 2 extra keywordarguments containing the config-namedtuples to be put in the respective functino
