### PR TITLE
Data input

### LINKED ISSUE #218: Channel_image should be more general
Currently it is super hardcoded:

- [x] number of channels and timing
- [x] sorting methods, there should be several ways of sorting allowed

### LINKED ISSUE #221: topoplotseries spacing
I think we should add the following info to the docs

To make the spacing of the topoplots more "tight" one has to modify two parameters:
```julia
with_theme(colgap=5) do 
	plot_topoplotseries!(f[2,3],df,0.1;positions=pos,
		axis=(;xlim_topo =(-0.05,1.05),ylim_topo=(-0.05,1.05)))
	end
```
Theoretically, colgap!(f,5) should work as well - but not if you subplot like I do in the example - not even if you generate a GridLayout before, because if I do f[2,3].layout I receive the global layout again and I do not know how to go from a `GridPosition` to a `GridLayout` (maybe you know?)

Note also that I think xlim_topo is deprecated, but I didnt dare to update that plot to a new version ;-) I think it should be `topoplot_axes=(;xlim = (-0.05,1.05))` etc.

### LINKED ISSUE #227: Contradiction in plot_topoplot signature
Why I see this error
```
julia>     plot_topoplot(dat[:, 50, 1])
ERROR: AssertionError: No positions found, did you forget to provide them via positions=XX, or labels=YY?
```
if according to signature positions are kwargs `plot_topoplot(data; positions = nothing, labels = nothing, kwargs...)`?
Some logical error here

### PR DESCRIPTION
**Pull request by vladdez**
fixed issues with more general data input #213:
- data inputs for `plot_channelimage(::DataFrame)`, `plot_erpgrid(::DataFrame)`, `plot_parallelcoordinates(::Matrix)`, `plot_topoplot(::Vector)`
- mistakes in signatures for `plot_butterfly` and `plot_erp`, moving some actions inside code from signatures
- updated docstrings
- adding sorting methods in arguments for channel image, arguments `sorting_variables` and `sorting_reverse`
- more tests for checking length mismatch of arguments in `plot_topoplot`, `plot_erpgrid` and `plot_channelimage`
- adding `ch_names::Vector{String}` into arguments for `plot_erpgrid`

Other
- fixed #227 
- fixed #218 
- fixed #221 
- typos in docs

### CODE REVIEW

File: docs/literate/how_to/hide_deco.jl [hunk 1]
```diff
@@ -54,14 +56,18 @@ plot_erpimage!(
...
 #=
 Some plots hide features by default. This could be reverted by setting the variables to `nothing`
 =#
 
 data, positions = TopoPlots.example_data()
 plot_topoplot(
-    data[:, 340, 1];
-    positions = positions,
+    data[:, 340, 1],
+    positions;
```
Comment (behinger) [inline docs/literate/how_to/hide_deco.jl:70]: this change depends on our discussion in #227. As indicated there, I'm not convinced this is a useful breaking change

**Review by behinger — COMMENTED** [review]
nice changes. But still blocked by #227
